### ISSUE TITLE
Catalog and document delivery links unavailable on first page load

### ISSUE THREAD

**Issue by jonearley** [mlibrary/mgetit#22] opened 2016-08-11 13:23 UTC
It seems to happen when online access is not available only, but it's tricky to replicate because once you find an example the next time you visit that page it has the links.

My guess would be these links are generated late and then stored and usable after the first page visit?

**Comment by jonearley** [comment] 2016-08-11 13:49
The bug can be reproduced when visiting the long url. The permalink does show catalog and document delivery links.

[Full Link](https://earleyj.www.lib.umich.edu/testapp/mgetit/resolve?ctx_ver=Z39.88-2004&ctx_enc=info%3Aofi%2Fenc%3AUTF-8&rfr_id=info%3Asid%2Fsummon.serialssolutions.com&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Ajournal&rft.genre=article&rft.atitle=Holiday+Traffic+Fatalities%2C+2008-2009+%5BOklahoma+Traffic+Accidents%5D%28Page+no.139+Table+no.161%29%3B2011+SRI+S6482-1&rft.date=2011-01-01&rft.externalDocID=2010_S6482_1_tbl161&rft.link_model=DirectLink&rft.summon_id=FETCH-proquest_statistical_2010_S6482_1_tbl1612&rft.bookmark=ePnHCXMw42LgTQStzc4rAe_hSuFkyPXIz8lMSaxUAJa-oGMRFNxAAxPg80J1FMDT76AReoVo_-ycRNCiGLg6x-Rk0MWaJcWxGgHAzKWQl68HbK8ohID2FIE5Zoaa1qAKTCE4yFMh2MwE2Fg05GbQd3MNcfbQhZWs8aCdOeBDj4ExB5r7jQerjDeML0nKARphRLoOADiUR2g&rft.link=http%3A%2F%2Fumich.summon.serialssolutions.com%2F2.0.0%2Flink%2F0%2FeLvHCXMwzV3dS8MwED8mBREEFRU_IQ8iE-xK1485RGTqyiYDp60gipS0aWHYtdNF0P_e3HUVYS97FPrQ0rS5JvTud5e7XwCO7DSyooSbumg6QretONEjt2XpTqRsRcrt1CzpiwfNjufcela3BlWy8Gx6K61Iqhora4i0WAHTfIouK_Jqf2bSmLxPyjP899RDFE2nQb4URUyO3PDe7-tB52rQPaYbjx-jC0NiVZKB68CG79oKYpqGjDKFfRpf42wJNFyqI_fs6XlORZPd8dag2hauzDYhWqcqOjhP6PgPPmsdlm-45MxP5AbUknwTxr0iGwn-zZRVRLoK5mHAiHhcTxmlReDKCXu5e8s4Jiv9tuvEMW54Kqev9aGSkOVFQ-FIFmD3dOGaJ-cILJj_0GczUbbA8LrBdU-vBiH8MwAhCh1Sy9AMS6Gb27DKMcs_l1QNKHaAxco7FG1-1rLaqZ1iNEZBDAVBW1y4dmw5u1Bf9PV7izfdh5UykozHAWipUgzJIWg04T82bOwd)

[Short Link (permalink)](https://earleyj.www.lib.umich.edu/testapp/mgetit/go/160)

**Comment by bertrama** [comment] 2016-08-17 16:18
That one was caused by a sql error.  The full link tried to save some data that was too large for a column. 
The short link only retrieved data that had been saved.  I'll restructure things to be recover from that situation better.

**Comment by varnum** [comment] 2016-08-23 14:29
Is this resolved, @bertrama ? I'm adding it to the public beta milestone.

**Comment by bertrama** [comment] 2016-08-23 15:04
It's probably fixed in development.

**Closed by bertrama** 2016-08-23 15:04 UTC
Labels: bug
